<?php
/**
 * This file is part of Hooks plugin for MyBB.
 *
 * This file contains the hooks you created in the Admin CP.
 * It must be writable in order for the Hooks plugin to work.
 *
 * DO NOT EDIT THIS FILE. IT WILL BE OVERWRITTEN BY THE HOOKS PLUGIN.
 *
 */

// Disallow direct access to this file for security reasons.
if(!defined("IN_MYBB"))
{
    die("Direct initialization of this file is not allowed.<br /><br />
         Please make sure IN_MYBB is defined.");
}

/* --- End of file. --- */
?>
